apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: carts-db
  name: carts-db-svc
  namespace: jx-staging
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: carts-db
status:
  loadBalancer: {}
